### ISSUE TITLE
After Effects export script producing error

### ISSUE THREAD

**Issue by alexicon3000** [unity3d-jp/MovieProxy#274] opened 2020-12-10 00:24 UTC
I'm attempting to use the included [After Effects export script](https://github.com/unity3d-jp/StreamingImageSequence/blame/dev/AE~/Plugins/AEjson.jsx) and getting this error after setting my directory: 
`Unable to execute script at line 213. Object of type String found where a Number, Array, or Property is needed. `

I'm using both the included example After Effects project file and a clean one of my own to test and I have tried the following workarounds without success:

I tried different versions of After Effects since this script was initially created with older versions of AE. The demo AE project appears to have been created with v14.2.1 and the [example video](https://www.youtube.com/watch?v=4og6rgQdb3c&feature=youtu.be) also uses 2017 CC. I tried these versions of AE:
- After Effects v17.5.1 (2020)
- The current After Effects Beta
- After Effects v16.1.3 (2019) 
_Unfortunately, versions earlier than 16.1.3 have been EOL'd by Adobe and don't appear to be available for download._ 

I have also tried switching the AE Expression Engine to **Legacy Extend Script** (Project Settings > Expressions) instead of the default of **JavaScript**.

Thanks for your great work on this package - it's extremely useful!

**Comment by sindharta** [comment] 2020-12-10 10:47
Thank you for letting us know.
I have confirmed this issue and we'll take a look.

**Comment by sindharta** [comment] 2020-12-16 06:39
@alexicon3000 
Fixed in https://github.com/unity3d-jp/StreamingImageSequence/pull/275

You should be able to execute the script using Adobe After Effects 2020 now.

**Comment by alexicon3000** [comment] 2020-12-17 18:10
@sindharta Thank you for your quick attention to that! 

I've tried swapping in the new version of the script from #275 and I'm running into a new issue. It seems that on import into Unity, the file path doesn't match the directory containing the image sequence. In the first screenshot below, the real location of the assets to be copied to Streaming Assets is in `~/Documents/[etc.]` For the first test below, I saved from AE into the same directory as the image sequence.

![ImportError](https://user-images.githubusercontent.com/1418667/102522768-a8554580-4064-11eb-83f8-3f7d63ee397d.png)

Then I noticed that if I save to a different directory the directory is concatenated and repeated twice: 
![ImportError2](https://user-images.githubusercontent.com/1418667/102525709-a1303680-4068-11eb-9268-24960cabfabd.png)

**Comment by sindharta** [comment] 2020-12-18 05:48
@alexicon3000 I can't seem to reproduce your issue using the [AE sample project](https://github.com/unity3d-jp/StreamingImageSequence/tree/dev/AE~/Samples) in this repo.

Is it possible for you to provide a simple sample of an AE project that you are trying to convert, plus let me know the steps (exact directory names, etc ) that you do to produce the error ?

**Comment by sindharta** [comment] 2021-03-04 05:40
Closing due to inactivity. Please feel free to reopen if necessary

**Closed as completed by sindharta** 2021-03-04 05:40 UTC
